version: '3'

services:
  mysql:
    container_name: clwy-api-mysql
    image: mysql:8.3.0
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_LOWER_CASE_TABLE_NAMES=0
    ports:
      - "13306:3306"
